name: Test and Deploy
on:
   push:
      branches:
         - main
jobs:
   test:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Install Dependency
           run: yarn install --frozen-lockfile

         - name: Run the tests
           run: yarn test
   deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
         - name: Connect and deploy to EC2
           uses: appleboy/ssh-action@v1.0.3
           with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER_NAME }}
              key: ${{ secrets.EC2_SSH }}
              port: 22
              script: |
                 export PATH=$PATH:/usr/local/bin  # Ensure yarn and pm2 are in PATH
                 # Navigate to your app directory
                 cd /home/${{ secrets.EC2_USER_NAME }}/react-test-app-amplify

                 # Verifying the navigation
                 ls -la

                 # Install Yarn if not already installed
                  if ! command -v yarn &> /dev/null; then
                  echo "Yarn is not installed. Installing Yarn..."
                  npm install -g yarn
                  fi

                  # Install PM2 if not already installed
                  if ! command -v pm2 &> /dev/null; then
                  echo "PM2 is not installed. Installing PM2..."
                  npm install -g pm2
                  fi

                 yarn install --frozen-lockfile

                 yarn build

                 pm2 restart my-react-app || pm2 start serve --name my-react-app -- -s dist -l 4173
