name: Matrix Demo
on:
   push:
      branches:
         - main
         - dev
jobs:
   test:
      runs-on: ubuntu-latest
      steps:
         - name: Checout code
           uses: actions/checkout@v3
         - name: List checkout files\
           run: ls
